-- Merchant setup: profile / location / payment-hub mutations.
--
-- The existing SELECT RLS is kept (members may read their merchant, locations,
-- and hubs). Direct INSERT/UPDATE from authenticated clients is revoked so
-- every mutation goes through these SECURITY DEFINER RPCs:
--   * update_merchant_profile
--   * create_merchant_location   (atomic location + permanent payment hub)
--   * update_merchant_location   (edit + deactivate/reactivate)
--   * ensure_location_payment_hub (idempotent get-or-create)
--
-- Public codes are generated by the existing payment_hubs trigger
-- (generate_payment_hub_public_code) — callers never supply them.
-- resolve_payment_hub is tightened so an inactive location cannot resolve.

-- ---------------------------------------------------------------------------
-- One active payment hub per location (NULLs remain allowed for legacy hubs
-- that are not bound to a location).
-- ---------------------------------------------------------------------------
create unique index if not exists payment_hubs_one_active_per_location
  on public.payment_hubs (merchant_location_id)
  where status = 'active' and merchant_location_id is not null;

-- ---------------------------------------------------------------------------
-- Private helpers (not granted to anon / authenticated)
-- ---------------------------------------------------------------------------
create or replace function app_private.null_trim(
  p_value text,
  p_field text,
  p_max int
)
returns text
language plpgsql
immutable
set search_path = public, pg_temp
as $$
declare
  v_value text := nullif(btrim(p_value), '');
begin
  if v_value is not null and char_length(v_value) > p_max then
    raise exception '% exceeds % characters', p_field, p_max;
  end if;
  return v_value;
end;
$$;

revoke all on function app_private.null_trim(text, text, int) from public;
grant execute on function app_private.null_trim(text, text, int) to service_role;

create or replace function app_private.require_merchant_manager(
  p_merchant_account_id uuid
)
returns uuid
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if p_merchant_account_id is null then
    raise exception 'merchant_account_id is required';
  end if;

  if not public.is_merchant_member(p_merchant_account_id, array['owner', 'admin']) then
    raise exception 'Not authorized' using errcode = '42501';
  end if;

  return v_uid;
end;
$$;

revoke all on function app_private.require_merchant_manager(uuid) from public;
grant execute on function app_private.require_merchant_manager(uuid) to service_role;

create or replace function app_private.normalize_website_url(p_value text)
returns text
language plpgsql
immutable
set search_path = public, pg_temp
as $$
declare
  v_value text := app_private.null_trim(p_value, 'website_url', 500);
begin
  if v_value is null then
    return null;
  end if;
  if v_value !~* '^https?://[^\s/$.?#].[^\s]*$' then
    raise exception 'website_url must be an http or https URL';
  end if;
  return v_value;
end;
$$;

revoke all on function app_private.normalize_website_url(text) from public;
grant execute on function app_private.normalize_website_url(text) to service_role;

create or replace function app_private.normalize_email(p_value text)
returns text
language plpgsql
immutable
set search_path = public, pg_temp
as $$
declare
  v_value text := app_private.null_trim(p_value, 'support_email', 254);
begin
  if v_value is null then
    return null;
  end if;
  if v_value !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'support_email is not a valid email address';
  end if;
  return lower(v_value);
end;
$$;

revoke all on function app_private.normalize_email(text) from public;
grant execute on function app_private.normalize_email(text) to service_role;

create or replace function app_private.normalize_country(p_value text)
returns text
language plpgsql
immutable
set search_path = public, pg_temp
as $$
declare
  v_value text := app_private.null_trim(p_value, 'country', 2);
begin
  if v_value is null then
    return 'US';
  end if;
  if char_length(v_value) <> 2 then
    raise exception 'country must be a 2-letter code';
  end if;
  return upper(v_value);
end;
$$;

revoke all on function app_private.normalize_country(text) from public;
grant execute on function app_private.normalize_country(text) to service_role;

create or replace function app_private.require_paired_coordinates(
  p_latitude double precision,
  p_longitude double precision
)
returns void
language plpgsql
immutable
set search_path = public, pg_temp
as $$
begin
  if (p_latitude is null) <> (p_longitude is null) then
    raise exception 'latitude and longitude must both be provided or both omitted';
  end if;
end;
$$;

revoke all on function app_private.require_paired_coordinates(double precision, double precision) from public;
grant execute on function app_private.require_paired_coordinates(double precision, double precision) to service_role;

-- ---------------------------------------------------------------------------
-- Internal: get or create the permanent active hub for an active location.
-- Caller must already have passed require_merchant_manager for the location's
-- merchant. Serializes on the location id so concurrent calls cannot create
-- two active hubs.
-- ---------------------------------------------------------------------------
create or replace function app_private.ensure_active_payment_hub(
  p_location_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_location public.merchant_locations%rowtype;
  v_hub public.payment_hubs%rowtype;
begin
  perform pg_advisory_xact_lock(
    hashtextextended('lokala.payment_hub:' || p_location_id::text, 0)
  );

  select * into v_location
  from public.merchant_locations
  where id = p_location_id;

  if not found then
    raise exception 'Location not found';
  end if;

  if v_location.status <> 'active' then
    raise exception 'Location is not active';
  end if;

  select * into v_hub
  from public.payment_hubs
  where merchant_location_id = p_location_id
    and status = 'active'
  order by created_at asc
  limit 1;

  if found then
    return jsonb_build_object(
      'payment_hub_id', v_hub.id,
      'public_code', v_hub.public_code,
      'merchant_account_id', v_hub.merchant_account_id,
      'merchant_location_id', v_hub.merchant_location_id,
      'status', v_hub.status,
      'idempotent', true
    );
  end if;

  -- Prefer reactivating the most recent hub so a printed QR keeps working.
  select * into v_hub
  from public.payment_hubs
  where merchant_location_id = p_location_id
  order by created_at desc
  limit 1;

  if found then
    update public.payment_hubs
    set status = 'active',
        disabled_at = null
    where id = v_hub.id
    returning * into v_hub;

    return jsonb_build_object(
      'payment_hub_id', v_hub.id,
      'public_code', v_hub.public_code,
      'merchant_account_id', v_hub.merchant_account_id,
      'merchant_location_id', v_hub.merchant_location_id,
      'status', v_hub.status,
      'idempotent', true
    );
  end if;

  insert into public.payment_hubs (
    merchant_account_id,
    merchant_location_id,
    status
  ) values (
    v_location.merchant_account_id,
    v_location.id,
    'active'
  )
  returning * into v_hub;

  return jsonb_build_object(
    'payment_hub_id', v_hub.id,
    'public_code', v_hub.public_code,
    'merchant_account_id', v_hub.merchant_account_id,
    'merchant_location_id', v_hub.merchant_location_id,
    'status', v_hub.status,
    'idempotent', false
  );
end;
$$;

revoke all on function app_private.ensure_active_payment_hub(uuid) from public;
grant execute on function app_private.ensure_active_payment_hub(uuid) to service_role;

create or replace function app_private.disable_location_payment_hubs(
  p_location_id uuid
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.payment_hubs
  set status = 'disabled',
      disabled_at = timezone('utc', now())
  where merchant_location_id = p_location_id
    and status = 'active';
end;
$$;

revoke all on function app_private.disable_location_payment_hubs(uuid) from public;
grant execute on function app_private.disable_location_payment_hubs(uuid) to service_role;

-- ---------------------------------------------------------------------------
-- update_merchant_profile
-- ---------------------------------------------------------------------------
create or replace function public.update_merchant_profile(
  p_merchant_account_id uuid,
  p_display_name text,
  p_legal_name text default null,
  p_description text default null,
  p_support_email text default null,
  p_support_phone text default null,
  p_website_url text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_name text;
  v_row public.merchant_accounts%rowtype;
begin
  perform app_private.require_merchant_manager(p_merchant_account_id);

  v_name := app_private.null_trim(p_display_name, 'display_name', 120);
  if v_name is null then
    raise exception 'display_name is required';
  end if;

  update public.merchant_accounts
  set
    display_name = v_name,
    legal_name = app_private.null_trim(p_legal_name, 'legal_name', 200),
    description = app_private.null_trim(p_description, 'description', 2000),
    support_email = app_private.normalize_email(p_support_email),
    support_phone = app_private.null_trim(p_support_phone, 'support_phone', 40),
    website_url = app_private.normalize_website_url(p_website_url)
  where id = p_merchant_account_id
  returning * into v_row;

  if not found then
    raise exception 'Merchant not found';
  end if;

  return jsonb_build_object(
    'merchant_account_id', v_row.id,
    'display_name', v_row.display_name,
    'legal_name', v_row.legal_name,
    'description', v_row.description,
    'support_email', v_row.support_email,
    'support_phone', v_row.support_phone,
    'website_url', v_row.website_url,
    'status', v_row.status
  );
end;
$$;

revoke all on function public.update_merchant_profile(uuid, text, text, text, text, text, text) from public;
grant execute on function public.update_merchant_profile(uuid, text, text, text, text, text, text) to authenticated;

-- ---------------------------------------------------------------------------
-- create_merchant_location — atomic location + permanent payment hub
-- ---------------------------------------------------------------------------
create or replace function public.create_merchant_location(
  p_merchant_account_id uuid,
  p_label text,
  p_address_text text default null,
  p_address_line1 text default null,
  p_address_line2 text default null,
  p_city text default null,
  p_region text default null,
  p_postal_code text default null,
  p_country text default 'US',
  p_latitude double precision default null,
  p_longitude double precision default null,
  p_timezone text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_label text;
  v_location public.merchant_locations%rowtype;
  v_hub jsonb;
  v_merchant_status text;
begin
  perform app_private.require_merchant_manager(p_merchant_account_id);
  perform app_private.require_paired_coordinates(p_latitude, p_longitude);

  v_label := app_private.null_trim(p_label, 'label', 120);
  if v_label is null then
    raise exception 'label is required';
  end if;

  select status into v_merchant_status
  from public.merchant_accounts
  where id = p_merchant_account_id;

  if not found then
    raise exception 'Merchant not found';
  end if;

  if v_merchant_status in ('suspended', 'closed') then
    raise exception 'Merchant is not accepting location changes';
  end if;

  insert into public.merchant_locations (
    merchant_account_id,
    label,
    address_text,
    address_line1,
    address_line2,
    city,
    region,
    postal_code,
    country,
    latitude,
    longitude,
    timezone,
    status
  ) values (
    p_merchant_account_id,
    v_label,
    app_private.null_trim(p_address_text, 'address_text', 500),
    app_private.null_trim(p_address_line1, 'address_line1', 200),
    app_private.null_trim(p_address_line2, 'address_line2', 200),
    app_private.null_trim(p_city, 'city', 100),
    app_private.null_trim(p_region, 'region', 100),
    app_private.null_trim(p_postal_code, 'postal_code', 20),
    app_private.normalize_country(p_country),
    p_latitude,
    p_longitude,
    app_private.null_trim(p_timezone, 'timezone', 64),
    'active'
  )
  returning * into v_location;

  -- A merchant with a live location is ready to present a public QR. Stripe
  -- readiness still gates actual redemption in a later phase.
  if v_merchant_status in ('draft', 'pending') then
    update public.merchant_accounts
    set status = 'active'
    where id = p_merchant_account_id
      and status in ('draft', 'pending');
  end if;

  v_hub := app_private.ensure_active_payment_hub(v_location.id);

  return jsonb_build_object(
    'location_id', v_location.id,
    'merchant_account_id', v_location.merchant_account_id,
    'label', v_location.label,
    'status', v_location.status,
    'payment_hub_id', v_hub ->> 'payment_hub_id',
    'public_code', v_hub ->> 'public_code',
    'idempotent', false
  );
end;
$$;

revoke all on function public.create_merchant_location(uuid, text, text, text, text, text, text, text, text, double precision, double precision, text) from public;
grant execute on function public.create_merchant_location(uuid, text, text, text, text, text, text, text, text, double precision, double precision, text) to authenticated;

-- ---------------------------------------------------------------------------
-- update_merchant_location
-- ---------------------------------------------------------------------------
create or replace function public.update_merchant_location(
  p_location_id uuid,
  p_label text,
  p_status text default 'active',
  p_address_text text default null,
  p_address_line1 text default null,
  p_address_line2 text default null,
  p_city text default null,
  p_region text default null,
  p_postal_code text default null,
  p_country text default 'US',
  p_latitude double precision default null,
  p_longitude double precision default null,
  p_timezone text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_existing public.merchant_locations%rowtype;
  v_label text;
  v_status text := lower(btrim(coalesce(p_status, 'active')));
  v_row public.merchant_locations%rowtype;
  v_hub jsonb;
begin
  if p_location_id is null then
    raise exception 'location_id is required';
  end if;

  select * into v_existing
  from public.merchant_locations
  where id = p_location_id;

  if not found then
    raise exception 'Location not found';
  end if;

  perform app_private.require_merchant_manager(v_existing.merchant_account_id);
  perform app_private.require_paired_coordinates(p_latitude, p_longitude);

  v_label := app_private.null_trim(p_label, 'label', 120);
  if v_label is null then
    raise exception 'label is required';
  end if;

  if v_status not in ('active', 'inactive') then
    raise exception 'status must be active or inactive';
  end if;

  update public.merchant_locations
  set
    label = v_label,
    status = v_status,
    address_text = app_private.null_trim(p_address_text, 'address_text', 500),
    address_line1 = app_private.null_trim(p_address_line1, 'address_line1', 200),
    address_line2 = app_private.null_trim(p_address_line2, 'address_line2', 200),
    city = app_private.null_trim(p_city, 'city', 100),
    region = app_private.null_trim(p_region, 'region', 100),
    postal_code = app_private.null_trim(p_postal_code, 'postal_code', 20),
    country = app_private.normalize_country(p_country),
    latitude = p_latitude,
    longitude = p_longitude,
    timezone = app_private.null_trim(p_timezone, 'timezone', 64)
  where id = p_location_id
  returning * into v_row;

  if v_status = 'inactive' then
    perform app_private.disable_location_payment_hubs(v_row.id);
  else
    v_hub := app_private.ensure_active_payment_hub(v_row.id);
  end if;

  if v_hub is null then
    select jsonb_build_object(
      'payment_hub_id', h.id,
      'public_code', h.public_code,
      'status', h.status
    )
    into v_hub
    from public.payment_hubs h
    where h.merchant_location_id = v_row.id
    order by h.created_at desc
    limit 1;
  end if;

  return jsonb_build_object(
    'location_id', v_row.id,
    'merchant_account_id', v_row.merchant_account_id,
    'label', v_row.label,
    'status', v_row.status,
    'payment_hub_id', v_hub ->> 'payment_hub_id',
    'public_code', v_hub ->> 'public_code',
    'hub_status', v_hub ->> 'status'
  );
end;
$$;

revoke all on function public.update_merchant_location(uuid, text, text, text, text, text, text, text, text, text, double precision, double precision, text) from public;
grant execute on function public.update_merchant_location(uuid, text, text, text, text, text, text, text, text, text, double precision, double precision, text) to authenticated;

-- ---------------------------------------------------------------------------
-- ensure_location_payment_hub — authenticated wrapper around the private helper
-- ---------------------------------------------------------------------------
create or replace function public.ensure_location_payment_hub(
  p_location_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_merchant_id uuid;
begin
  if p_location_id is null then
    raise exception 'location_id is required';
  end if;

  select merchant_account_id into v_merchant_id
  from public.merchant_locations
  where id = p_location_id;

  if v_merchant_id is null then
    raise exception 'Location not found';
  end if;

  perform app_private.require_merchant_manager(v_merchant_id);

  return app_private.ensure_active_payment_hub(p_location_id);
end;
$$;

revoke all on function public.ensure_location_payment_hub(uuid) from public;
grant execute on function public.ensure_location_payment_hub(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Public resolver: also require the bound location (when present) to be active.
-- Unbound hubs (merchant_location_id is null) keep the previous behavior.
-- ---------------------------------------------------------------------------
create or replace function public.resolve_payment_hub(p_public_code text)
returns table (
  payment_hub_id uuid,
  public_code text,
  merchant_account_id uuid,
  merchant_display_name text,
  merchant_location_id uuid,
  location_label text,
  currency text
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if p_public_code is null or length(trim(p_public_code)) = 0 then
    return;
  end if;

  return query
  select
    h.id,
    h.public_code,
    h.merchant_account_id,
    ma.display_name,
    h.merchant_location_id,
    ml.label,
    'USD'::text
  from public.payment_hubs h
  join public.merchant_accounts ma on ma.id = h.merchant_account_id
  left join public.merchant_locations ml on ml.id = h.merchant_location_id
  where h.public_code = trim(p_public_code)
    and h.status = 'active'
    and ma.status = 'active'
    and (ml.id is null or ml.status = 'active');
end;
$$;

revoke all on function public.resolve_payment_hub(text) from public;
grant execute on function public.resolve_payment_hub(text) to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Least privilege: authenticated clients may SELECT merchant data they belong
-- to, but may not write tables directly. Mutations go through the RPCs above.
-- ---------------------------------------------------------------------------
revoke insert, update, delete on public.merchant_locations from authenticated;
revoke update, insert, delete on public.merchant_accounts from authenticated;
revoke insert, update, delete on public.payment_hubs from authenticated;

grant select on public.merchant_accounts to authenticated;
grant select on public.merchant_locations to authenticated;
grant select on public.payment_hubs to authenticated;

drop policy if exists merchant_accounts_update_owner_admin on public.merchant_accounts;
drop policy if exists merchant_locations_write_owner_admin on public.merchant_locations;
drop policy if exists merchant_locations_update_owner_admin on public.merchant_locations;
